# -*- coding: utf-8 -*-
"""20220816 정지민 융합프로젝트구현과제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wNnVN6OQ3t9lJ7QkuN92FjrZAVFYNfR9
"""

#아래의 품목들은 원래 옷장에 등록되어 있다고 가정한다.
#아래의 리스트에서 옷을 추가하거나 삭제할 수 있다.

#상의
up1list=['긴팔티','셔츠'] #봄
up2list=['반팔티','나시'] #여름
up3list=['후드티','맨투맨'] #가을
up4list=['롱패딩','숏패딩','무스탕'] #겨울

#하의
do1list=['긴바지','슬랙스'] #봄
do2list=['반바지','치마'] #여름
do3list=['레깅스','롱스커트','청바지'] #가을
do4list=['기모바지','기모스타킹','히트텍'] #겨울

#기타
ac1list=['볼캡','비니'] #맑음
ac2list=['미니선풍기','부채','양산'] #쨍쨍
ac3list=['우산','우비'] #비
ac4list=['우산','목도리','장갑'] #눈


re_list=[] #최종 추천

sum=0
import random


while True:

  st = int(input('<오늘의 코디> 앱을 실행하였습니다. 옷장 관리:1, 옷 추천 받기:2, 앱 종료:3 -> '))

  if st == 1:
  
    while True:

      st1 = int(input('옷장이 열렸습니다. 옷 등록:1, 옷 삭제:2, 옷장 닫기(전 화면으로 돌아가기):3 -> '))
      
      if st1 == 1: #옷 등록
        print('\n현재 옷장에 저장된 품목을 참고해주세요.\n상의 -> 봄:',up1list,'여름:', up2list,'가을:',up3list,'겨울:', up4list)
        print('하의 -> 봄:',do1list,'여름:', do2list,'가을:',do3list,'겨울:', do4list)
        print('기타 -> 맑음:',ac1list,'쨍쨍:', ac2list,'비:', ac3list,'눈:', ac4list,'\n')

        st2 = int(input('등록하고싶은 품목의 카테고리를 골라주세요. 상의:1, 하의:2, 기타:3 -> '))
        if st2 == 1: #상의
          st3 = int(input('등록하고싶은 상의의 계절을 골라주세요. 봄:1, 여름:2, 가을:3, 겨울:4 -> '))
          if st3 ==1:
            up1list.append(input('품목이 무엇인가요?'))
          elif st3 ==2:
            up2list.append(input('품목이 무엇인가요?'))
          elif st3==3:
            up3list.append(input('품목이 무엇인가요?'))
          elif st3==4:
            up4list.append(input('품목이 무엇인가요?'))
          else:
            print('잘못 입력하셨습니다. 전 화면으로 돌아갑니다.\n')
            continue
        elif st2 == 2: #하의
          st3 = int(input('등록하고싶은 하의의 계절을 골라주세요. 봄:1, 여름:2, 가을:3, 겨울:4 -> '))
          if st3 ==1:
            do1list.append(input('품목이 무엇인가요?'))
          elif st3 ==2:
            do2list.append(input('품목이 무엇인가요?'))
          elif st3==3:
            do3list.append(input('품목이 무엇인가요?'))
          elif st3==4:
            do4list.append(input('품목이 무엇인가요?'))
          else:
            print('잘못 입력하셨습니다. 전 화면으로 돌아갑니다.\n')
            continue
        elif st2 == 3: #기타
          st3 = int(input('등록하고싶은 기타품목의 날씨를 골라주세요. 맑음:1, 쨍쨍:2, 비:3, 눈:4 -> '))
          if st3 ==1:
            ac1list.append(input('품목이 무엇인가요?'))
          elif st3 ==2:
            ac2list.append(input('품목이 무엇인가요?'))
          elif st3==3:
            ac3list.append(input('품목이 무엇인가요?'))
          elif st3==4:
            ac4list.append(input('품목이 무엇인가요?'))
          else:
            print('잘못 입력하셨습니다. 전 화면으로 돌아갑니다.\n')
            continue
        else:
          print('잘못 입력하셨습니다. 전 화면으로 돌아갑니다.\n')
          continue
          



      elif st1 == 2: #옷삭제
        print('\n현재 옷장에 저장된 품목을 참고해주세요.\n상의 -> 봄:',up1list,'여름:', up2list,'가을:',up3list,'겨울:', up4list)
        print('하의 -> 봄:',do1list,'여름:', do2list,'가을:',do3list,'겨울:', do4list)
        print('기타 -> 맑음:',ac1list,'쨍쨍:', ac2list,'비:', ac3list,'눈:', ac4list,'\n')

        st2 = int(input('삭제하고싶은 품목의 카테고리를 골라주세요. 상의:1, 하의:2, 기타:3 -> '))
        if st2 == 1: #상의
          st3 = int(input('삭제하고싶은 상의의 계절을 골라주세요. 봄:1, 여름:2, 가을:3, 겨울:4 -> '))
          if st3 ==1:
            up1list.remove(input('품목이 무엇인가요?'))
          elif st3 ==2:
            up2list.remove(input('품목이 무엇인가요?'))
          elif st3==3:
            up3list.remove(input('품목이 무엇인가요?'))
          elif st3==4:
            up4list.remove(input('품목이 무엇인가요?'))
          else:
            print('잘못 입력하셨습니다. 전 화면으로 돌아갑니다.\n')
            continue
        elif st2 == 2: #하의
          st3 = int(input('삭제하고싶은 하의의 계절을 골라주세요. 봄:1, 여름:2, 가을:3, 겨울:4 -> '))
          if st3 ==1:
            do1list.remove(input('품목이 무엇인가요?'))
          elif st3 ==2:
            do2list.remove(input('품목이 무엇인가요?'))
          elif st3==3:
            do3list.remove(input('품목이 무엇인가요?'))
          elif st3==4:
            do4list.remove(input('품목이 무엇인가요?'))
          else:
            print('잘못 입력하셨습니다. 전 화면으로 돌아갑니다.\n')
            continue
        elif st2 == 3: #기타 
          st3 = int(input('삭제하고싶은 기타물품의 날씨를 골라주세요. 맑음:1, 쨍쨍:2, 비:3, 눈:4 -> '))
          if st3 ==1:
            ac1list.remove(input('품목이 무엇인가요?'))
          elif st3 ==2:
            ac2list.remove(input('품목이 무엇인가요?'))
          elif st3==3:
            ac3list.remove(input('품목이 무엇인가요?'))
          elif st3==4:
            ac4list.remove(input('품목이 무엇인가요?'))
          else:
            print('잘못 입력하셨습니다. 전 화면으로 돌아갑니다.\n')
            continue
        else:
          print('잘못 입력하셨습니다. 전 화면으로 돌아갑니다.\n')
          continue


      elif st1 == 3: #옷장 닫기(전 화면으로 돌아가기)
        print('\n')
        break
      
      else:
        print('잘못 입력하셨습니다. 다시 입력해주세요.\n')
        continue

      print('\n옷장이 다음과 같이 저장되었습니다:)\n상의 -> 봄:',up1list,'여름:', up2list,'가을:',up3list,'겨울:', up4list)
      print('하의 -> 봄:',do1list,'여름:', do2list,'가을:',do3list,'겨울:', do4list)
      print('기타 -> 맑음:',ac1list,'쨍쨍:', ac2list,'비:', ac3list,'눈:', ac4list,'\n\n')



  elif st == 2: #옷 추천
    print('\n>>주의사항<< 옷장에 옷이 하나라도 들어있어야 추천을 받으실 수 있습니다!')
    print('현재의 계절과 날씨를 하나씩 차례대로 골라주세요.')

    weth = int(input('계절을 골라주세요. 봄:1, 여름:2, 가을:3, 겨울:4, 전 화면으로 돌아가기:5 -> '))

    if weth==1:
      re_list.append(random.choice(up1list))
      re_list.append(random.choice(do1list))
    elif weth==2:
      re_list.append(random.choice(up2list))
      re_list.append(random.choice(do2list))
    elif weth==3:
      re_list.append(random.choice(up3list))
      re_list.append(random.choice(do3list))
    elif weth==4:
      re_list.append(random.choice(up4list))
      re_list.append(random.choice(do4list))
    elif weth==5:
      print('\n')
      continue
    else:
      print('잘못 입력하셨습니다. 전 화면으로 돌아갑니다.\n')
      continue


    we = int(input('날씨를 골라주세요. 맑음:1, 쨍쨍:2, 비:3, 눈:4 -> '))
    if we ==1:
      re_list.append(random.choice(ac1list))
    elif we ==2:
      re_list.append(random.choice(ac2list))
    elif we==3:
      re_list.append(random.choice(ac3list))
    elif we==4:
      re_list.append(random.choice(ac4list))
    else:
      print('잘못 입력하셨습니다. 전 화면으로 돌아갑니다.\n')
      continue

    sum=sum+1;

    print('\n*****두구두구... 오늘의 추천 코디 결과는?*****')
    print('오늘의 추천 상의는 %s이고, 추천 하의는 %s입니다.'%(re_list[0],re_list[1]))
    print('또한 오늘은 %s을(를) 함께 가지고 가시는게 좋을 것 같습니다.'%re_list[2])
    print('오늘의 코디 앱을 사용해주셔서 감사합니다:) 현재 이용 횟수는',sum,'회 입니다.\n\n')
    
    re_list=[]





  elif st == 3: #앱 종료
    print('\n<오늘의 코디>앱을 종료하겠습니다. 이용해주셔서 감사합니다:)')
    break


  else:
    print('잘못 입력하셨습니다. 다시 입력해주세요.\n')